/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: CoinLore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.gy4ez8.yaccpt.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @property `data`
 * @property info
 */
@JsonClass(generateAdapter = true)
data class CoinsResponse(
    @Json(name = "data") @field:Json(name = "data") var `data`: List<Coin>,
    @Json(name = "info") @field:Json(name = "info") var info: CoinsResponseInfo
)
