/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: CoinLore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.gy4ez8.yaccpt.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * 
 * @property id
 * @property symbol
 * @property name
 * @property nameid
 * @property rank
 * @property priceUsd
 * @property percentChange24h
 * @property percentChange1h
 * @property percentChange7d
 * @property marketCapUsd
 * @property volume24
 * @property volume24Native
 * @property csupply
 * @property priceBtc
 * @property tsupply
 * @property msupply
 */
@JsonClass(generateAdapter = true)
data class Coin(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "symbol") @field:Json(name = "symbol") var symbol: String?,
    @Json(name = "name") @field:Json(name = "name") var name: String?,
    @Json(name = "nameid") @field:Json(name = "nameid") var nameid: String? = null,
    @Json(name = "rank") @field:Json(name = "rank") var rank: BigDecimal? = null,
    @Json(name = "price_usd") @field:Json(name = "price_usd") var priceUsd: String? = null,
    @Json(name = "percent_change_24h") @field:Json(name = "percent_change_24h") var percentChange24h: String? = null,
    @Json(name = "percent_change_1h") @field:Json(name = "percent_change_1h") var percentChange1h: String? = null,
    @Json(name = "percent_change_7d") @field:Json(name = "percent_change_7d") var percentChange7d: String? = null,
    @Json(name = "market_cap_usd") @field:Json(name = "market_cap_usd") var marketCapUsd: String? = null,
    @Json(name = "volume24") @field:Json(name = "volume24") var volume24: String? = null,
    @Json(name = "volume24_native") @field:Json(name = "volume24_native") var volume24Native: String? = null,
    @Json(name = "csupply") @field:Json(name = "csupply") var csupply: String? = null,
    @Json(name = "price_btc") @field:Json(name = "price_btc") var priceBtc: String? = null,
    @Json(name = "tsupply") @field:Json(name = "tsupply") var tsupply: String? = null,
    @Json(name = "msupply") @field:Json(name = "msupply") var msupply: String? = null
)
