/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: CoinLore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.gy4ez8.yaccpt.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * @property coinsNum
 * @property time
 */
@JsonClass(generateAdapter = true)
data class CoinsResponseInfo(
    @Json(name = "coins_num") @field:Json(name = "coins_num") var coinsNum: BigDecimal,
    @Json(name = "time") @field:Json(name = "time") var time: BigDecimal
)
