/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: CoinLore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.gy4ez8.yaccpt.model

/**
 * 
 */
typealias CoinResponse = List<Coin>
