/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: CoinLore
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.gy4ez8.yaccpt.network

import hu.gy4ez8.yaccpt.model.Coin
import hu.gy4ez8.yaccpt.model.CoinResponse
import hu.gy4ez8.yaccpt.model.CoinsResponse
import retrofit2.Call
import retrofit2.http.*

@JvmSuppressWildcards
interface CoinsApi {
    /**
     * Add a coin
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: add-coin",
        "Content-Type: application/json"
    )
    @POST("tickers/")
    fun addCoin(@retrofit2.http.Body coin: Coin?): Call<Coin>
    /**
     * Delete a coin
     * The endpoint is owned by defaultname service owner
     * @param id (optional)
     */
    @Headers(
        "X-Operation-ID: delete-coin",
        "Content-Type: application/json"
    )
    @DELETE("ticker/")
    fun deleteCoin(
        @retrofit2.http.Query("id") id: String?
    ): Call<Void>
    /**
     * Get coin details
     * The endpoint is owned by defaultname service owner
     * @param id (optional)
     */
    @Headers(
        "X-Operation-ID: get-coin",
        "Content-Type: application/json"
    )
    @GET("ticker/")
    fun getCoin(
        @retrofit2.http.Query("id") id: String?
    ): Call<CoinResponse>
    /**
     * Get all coins
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: get-coins",
        "Content-Type: application/json"
    )
    @GET("tickers/")
    fun getCoins(): Call<CoinsResponse>
    /**
     * Update a coin
     * The endpoint is owned by defaultname service owner
     * @param id (optional)
     */
    @Headers(
        "X-Operation-ID: update-coin",
        "Content-Type: application/json"
    )
    @PUT("ticker/")
    fun updateCoin(
        @retrofit2.http.Query("id") id: String?,
        @retrofit2.http.Body coin: Coin?
    ): Call<Coin>
}
